version: "3.8"
services:
  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser

  app:
    image: ruby:3.0.2
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      DB_USER: pguser
      DB_PASS: pgpass
      DB_HOST: db
    working_dir: /app

volumes:
  db-data:
  bundle:
