version: "3.8"
services:
  app:
    build: .
    environment:
      APP_DB_USERNAME: "postgrestestuser"
      APP_DB_PASSWORD: "postgrestestpass"
      APP_DB_HOST: "db"
      APP_DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgrestestpass"
      POSTGRES_USER: "postgrestestuser"
      POSTGRES_DB: "testdb"
